### ISSUE TITLE
Feature Request: Needs Gitpod

### ISSUE THREAD

**Issue by LinuxGamer** [TechSquidTV/Shoutify#18]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe it.

Put Gitpod to allow people to contribute online

### Describe the solution you'd like.

Add gitpod link

**Comment by KyleTryon** [comment]
How does gitpod compare to GitHub Spaces?

**Comment by LinuxGamer** [comment]
And works faster in my experience
