### ISSUE TITLE
Feature Request: Add License

### ISSUE THREAD

**Issue by LinuxGamer** [TechSquidTV/Shoutify#19]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe it.

Add a MIT License

### Describe the solution you'd like.

Add MIT license

**Comment by KyleTryon** [comment]
Considering updating to Apache 2.0 in order to protect the logo. Any thoughts?

https://choosealicense.com/licenses/

**Comment by Njong392** [comment]
> Considering updating to Apache 2.0 in order to protect the logo. Any thoughts?
> 
> https://choosealicense.com/licenses/

Just got to read about the differences between Apache 2.0 and the MIT license. I think adding Apache has a significant advantage. Sounds good to me I guess. But found [this article](https://soos.io/apache-vs-mit-license/) that summarises pros and cons nicely.

**Comment by TAKANOME-DEV** [comment]
> > Considering updating to Apache 2.0 in order to protect the logo. Any thoughts?
> > https://choosealicense.com/licenses/
> 
> Just got to read about the differences between Apache 2.0 and the MIT license. I think adding Apache has a significant advantage. Sounds good to me I guess. But found [this article](https://soos.io/apache-vs-mit-license/) that summarises pros and cons nicely.

After reading this article, I think Apache 2.0 is a good choice, thanks @Njong392
