### ISSUE TITLE
Cannot start the app

### ISSUE THREAD

**Issue by TAKANOME-DEV** [TechSquidTV/Shoutify#2]
I just cloned the repo,  install the dependencies and start the app. I got the following error message:
```sh
❌ Invalid environment variables:
 DATABASE_URL: Required
 NEXTAUTH_SECRET: Required
 NEXTAUTH_URL: Required
 DISCORD_CLIENT_ID: Required
 DISCORD_CLIENT_SECRET: Required
```
Can you please give me more information about the environment variables?

**Comment by KyleTryon** [comment]
Hello,

The app is still in very early stages of development and is not yet ready to be deployed. This information will be updated as progress is made and developer documentation will be released.

I expect it might be about a month before we have an MVP that is fully working. I am going to close this issue for now but thank you for checking out the project.
