### ISSUE TITLE
Bug: Make app navigation responsive

### ISSUE THREAD

**Issue by KyleTryon** [TechSquidTV/Shoutify#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="258" alt="image" src="https://user-images.githubusercontent.com/33272306/190277965-2c867d37-16b4-4f39-8208-d63ab1c96e56.png">
<img width="233" alt="image" src="https://user-images.githubusercontent.com/33272306/190277989-aecfa2df-0246-43fa-ba00-f556dbf4e31e.png">
<img width="482" alt="image" src="https://user-images.githubusercontent.com/33272306/190278012-a0e68d3c-5044-420b-ac91-8e1462f08200.png">

### Steps to reproduce

use chrome dev tools to show different devices and screen sizes.

### Expected behavior

1. Ensure the nav bar extends the full length of the page
2. When small enough, the menu should no longer expand and should stay in the closed state. This functionality can easily be added now with the latest PR change: https://github.com/TechSquidTV/Shoutify/pull/23/files

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

The nav component can be found here: https://github.com/TechSquidTV/Shoutify/blob/main/src/components/nav/AppNav.tsx
The nav is loaded as part of the page layout: https://github.com/TechSquidTV/Shoutify/blob/main/src/layouts/AppLayout.tsx
  - I suspect the layout isn't full-height.

**Comment by TAKANOME-DEV** [comment]
@KyleTryon can you assign me this?

**Comment by KyleTryon** [comment]
> @KyleTryon can you assign me this?

Assigned.
