### ISSUE TITLE
Feature Request: Add horizontal navbar for mobile view

### ISSUE THREAD

**Issue by TAKANOME-DEV** [TechSquidTV/Shoutify#31]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe it.

Currently when you switch to mobile view, you have to scroll horizontally to be able to post a tweet.
Take a look :arrow_down: :

| ![layout_1](https://user-images.githubusercontent.com/79809121/190925944-9afc6921-fb09-4ba6-b4aa-589d83a1ddf2.png) 	| ![layout_1_1](https://user-images.githubusercontent.com/79809121/190925947-85709736-3efc-4dd3-b82a-6b8f08a1eaef.png) 	|
|--------------------------------------------------------------------------------------------------------------------	|----------------------------------------------------------------------------------------------------------------------	|
|                                                                                                                    	|                                                                                                                      	|

### Describe the solution you'd like.

It would be nice if we hide the sidebar and show a horizontal navbar at the top with an icon to open the sidebar
And perhaps add the logo and what not :sweat_smile: 

### What is the motivation / use case for changing the behavior?

I think it can facilitate posting tweets and improve user experince

**Comment by KyleTryon** [comment]
I think it would be possible to fix the scroll issue. But, with limited screen real estate on small devices, maybe it would be a good idea to have an "overlay" nav on small devices, which takes up the full screen when open and minimizes to only a hamburger icon when on mobile.

**Comment by TAKANOME-DEV** [comment]
Absolutely we can do something like that :100:

**Comment by yash91989201** [comment]
If there are no PR's fixing this issue could you please assign it to me. I would love to contribute

**Comment by yash91989201** [comment]
Could you assign the issue to me? I can make the changes as required

**Comment by TAKANOME-DEV** [comment]
@yash91989201 sure you can take it.
I would suggest that you wait until @KyleTryon  assign it to you before you start working on it :fist_oncoming: 
I'm not sure if this feature is needed for now

**Comment by yash91989201** [comment]
> @yash91989201 sure you can take it.
> I would suggest that you wait until @KyleTryon  assign it to you before you start working on it :fist_oncoming: 
> I'm not sure if this feature is needed for now 

Yeah, sure

**Comment by KyleTryon** [comment]
Hey folks, 
I will assign you @yash91989201, thank you.
