### ISSUE TITLE
Bug: Get an error on adding a commit

### ISSUE THREAD

**Issue by mfts** [TechSquidTV/Shoutify#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I want to make a commit to a fork of the repo and get an error message (for more details see full log message below)

```
✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
✔ Cleaning up temporary files...
npm ERR! canceled

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2022-09-22T16_24_21_143Z-debug-0.log
husky - commit-msg hook exited with code 1 (error)
```

### Steps to reproduce

1. Change some text in `hacking.md` 
2. stage changes
3. add a commit w/ message: `git commit -m "docs(hacking): add note to get Twitter API credentials"`
4. error (see logs below)

### Expected behavior

I can make a commit to a branch

### Shoutify app version

0.1.0

### Node.js version

v16.17.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

This is the log content from using it inside GitPod. Same message appears locally using Node LTS.

```
0 verbose cli /home/gitpod/.nvm/versions/node/v16.17.0/bin/node /home/gitpod/.nvm/versions/node/v16.17.0/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@8.15.0
2 info using node@v16.17.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/gitpod/.nvm/versions/node/v16.17.0/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/workspace/Shoutify/.npmrc Completed in 1ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/home/gitpod/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/gitpod/.nvm/versions/node/v16.17.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 timing npm:load:configload Completed in 11ms
20 timing npm:load:mkdirpcache Completed in 3ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm exec commitlint --edit .git/COMMIT_EDITMSG
23 verbose argv "exec" "--no-yes" "--" "commitlint" "--edit" ".git/COMMIT_EDITMSG"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:/home/gitpod/.npm/_logs
28 verbose logfile /home/gitpod/.npm/_logs/2022-09-22T16_24_21_143Z-debug-0.log
29 timing npm:load:logFile Completed in 5ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 25ms
33 silly logfile done cleaning log files
34 timing arborist:ctor Completed in 1ms
35 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
36 http fetch GET 200 https://registry.npmjs.org/commitlint 102ms (cache revalidated)
37 timing arborist:ctor Completed in 0ms
38 timing command:exec Completed in 1707ms
39 verbose stack Error: canceled
39 verbose stack     at exec (/home/gitpod/.nvm/versions/node/v16.17.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:177:17)
39 verbose stack     at async module.exports (/home/gitpod/.nvm/versions/node/v16.17.0/lib/node_modules/npm/lib/cli.js:78:5)
40 verbose cwd /workspace/Shoutify
41 verbose Linux 5.15.0-47-generic
42 verbose node v16.17.0
43 verbose npm  v8.15.0
44 error canceled
45 verbose exit 1
46 timing npm Completed in 1789ms
47 verbose code 1
48 error A complete log of this run can be found in:
48 error     /home/gitpod/.npm/_logs/2022-09-22T16_24_21_143Z-debug-0.log
```

**Comment by TAKANOME-DEV** [comment]
Hi@mfts, I had the same mistake when I tried to commit my code. There is definitely a problem here, but I don't know if it's `commitlint` or `pre-ommit hook` but you can use the `--no-verify` flag when committing for now : `git commit -m "message" --no-verify`

**Comment by mfts** [comment]
Thanks @TAKANOME-DEV for the tip. 

Not sure where the problem is but the setup of `commitlint` with husky is 100% correct. I double-checked their documentation.

**Comment by mfts** [comment]
Another issue I found is that there are 22 npm package issues (21 of which are critical according to npm) that should also be fixed sooner than later.

**Comment by TAKANOME-DEV** [comment]
> Thanks @TAKANOME-DEV for the tip.
> 
> Not sure where the problem is but the setup of `commitlint` with husky is 100% correct. I double-checked their documentation.

Oh, that's great, hope we will find out soon what's going on here :100:

**Comment by TAKANOME-DEV** [comment]
> Another issue I found is that there are 22 npm package issues (21 of which are critical according to npm) that should also be fixed sooner than later.

Don't worry, this is related to Storybook which use outdated packages, but they will soon release v7 with most of these issues fixed :pray:

**Comment by KyleTryon** [comment]
@mfts You can use `--no-verify` on your commit message for now to bypass this.
@TAKANOME-DEV appreciate your help here 🙇
