### ISSUE TITLE
Linking License and Contributing Guidelines to the ReadMe

### ISSUE THREAD

**Issue by krupalitrivedi** [TechSquidTV/Shoutify#39]
Hello! When I was trying to find the Contributing Guidelines for the project, I was unable to find them.
It will be better if you change the directory of the file. 

An example of how the Contributing file would be easy to navigate,
![image](https://user-images.githubusercontent.com/99717469/192574347-84e9819c-3448-4b67-97cd-4ce488989767.png)

Along with that, I recommend linking guidelines and the license towards the end of the ReadMe file so it becomes easier for people on phones and computers as well to navigate easily!

**Comment by KyleTryon** [comment]
Hey @krupalitrivedi 👋 
Both relevant contributing docs are linked under the contributing section of the readme: 
https://github.com/TechSquidTV/Shoutify#contributing

[GitHub suggests](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) placing the docs within either the root, (as you suggested), a `docs` directory (which we may use for product documentation in the future), or within the `.github` directory. 

As the list of files in the root is growing quite large, pushing the readme farther down the page, I am attempting to move any file that does not need to be in the root, out of it currently, to give more room for the `README.md`, but all relevant links are within.

We are however missing the license as you mentioned, I'll get us a badge for the license 👍 . Thanks for the suggestion

**Comment by KyleTryon** [comment]
License badge added: https://github.com/TechSquidTV/Shoutify/commit/553183a079dd1b2d47f976cc4df20e4d5b02e088
Thank you!
